[options]
  bootstrap_before = "myspacevim#before"
  bootstrap_after = "myspacevim#after"
  buffer_index_type = 4
  colorscheme = "gruvbox"
  colorscheme_bg = "dark"
  enable_guicolors = true
  enable_statusline_mode = true
  enable_tabline_filetype_icon = true
  enable_vimfiler_gitstatus = true
  filemanager = "nerdtree"
  filetree_direction = "left"
  github_username = "joelazar"
  relativenumber = true
  statusline_inactive_separator = "bar"
  statusline_separator = "arrow"
  statusline_unicode_symbols = false
  enable_statusline_bfpath = true
  terminal_cursor_shape = 1
  vimcompatible = false
  windows_index_type = 3
  windows_leader = "s"

[[layers]]
  name = 'core'

[[layers]]
  name = 'format'
  enable = true
  format_on_save = true

[[layers]]
  name = 'autocomplete'
  autocomplete_method = "coc"
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "cycle"
  autocomplete_parens = false

[[layers]]
  name = 'lsp'
  filetypes = [
    'c',
    'cpp',
    'go',
    'javascript',
    'python',
    'sh'
  ]
    [layers.override_cmd]
      go = ['gopls']

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 40

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "debug"

[[layers]]
  name = "git"

[[layers]]
  name = "fzf"

[[layers]]
  name = "incsearch"

[[layers]]
  name = "sudo"

[[layers]]
  name = 'test'

[[layers]]
  name = "tools"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#json"

[[layers]]
  name = "lang#latex"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#ipynb"

# [[custom_plugins]]
#   repo = "glacambre/firenvim"

[[custom_plugins]]
  repo = "iamcco/coc-tailwindcss"
  on_cmd = ["yarn install --frozen-lockfile && yarn run build"]
