[options]
  autocomplete_method = "coc"
  autocomplete_parens = true
  bootstrap_after = "myspacevim#after"
  bootstrap_before = "myspacevim#before"
  buffer_index_type = 4
  colorscheme = "gruvbox"
  colorscheme_bg = "dark"
  default_indent = 4
  enable_guicolors = true
  enable_statusline_bfpath = true
  enable_statusline_mode = true
  enable_tabline_filetype_icon = true
  enable_vimfiler_gitstatus = true
  enable_vimfiler_welcome = true
  expand_tab = true
  filemanager = "nerdtree"
  filetree_direction = "left"
  filetree_show_hidden = true
  github_username = "joelazar"
  guifont = "Hack Nerd Font:h20"
  lint_on_the_fly = true
  max_column = 120
  relativenumber = true
  snippet_engine = "ultisnips"
  statusline_inactive_separator = "bar"
  statusline_separator = "arrow"
  statusline_unicode_symbols = true
  terminal_cursor_shape = 1
  vimcompatible = false
  windows_index_type = 3
  windows_leader = "s"

[[layers]]
  name = 'core'

[[layers]]
  name = 'format'
  enable = true
  format_on_save = false

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "cycle"

[[layers]]
  name = 'lsp'
  filetypes = [
    'c',
    'css',
    'cpp',
    'go',
    'html',
    'javascript',
    'python',
    'sh',
    'typescript'
  ]

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 40

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "debug"

[[layers]]
  name = "git"

[[layers]]
  name = "fzf"

[[layers]]
  name = "incsearch"

[[layers]]
  name = "sudo"

[[layers]]
  name = 'test'

[[layers]]
  name = "tools"

# [[layers]]
#   name = "lang#c"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#go"
  format_on_save = true

[[layers]]
  name = "lang#javascript"
  format_on_save = true

[[layers]]
  name = "lang#json"

[[layers]]
  name = "lang#latex"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#python"
  format_on_save = true

[[layers]]
  name = "lang#sh"
  format_on_save = true

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#ipynb"

[[layers]]
  name = "lang#lua"

# https://github.com/SpaceVim/SpaceVim/issues/4142
# [[layers]]
#   name = "VersionControl"

# [[layers]]
#   name = "foldsearch"

[[custom_plugins]]
  repo = "metakirby5/codi.vim"

[[custom_plugins]]
  repo = "nvim-treesitter/nvim-treesitter"

[[custom_plugins]]
  repo = "equalsraf/neovim-gui-shim"

[[custom_plugins]]
  repo = "mcchrish/nnn.vim"

[[custom_plugins]]
  repo = "kdheepak/lazygit.nvim"

[[custom_plugins]]
  repo = "tyru/open-browser.vim"

[[custom_plugins]]
  repo = "tyru/open-browser-github.vim"

# [[custom_plugins]]
#   repo = "soywod/himalaya"

# [[custom_plugins]]
#   repo = "glacambre/firenvim"
