[metadata]
name = "alias"
description = "A channel to select from shell aliases"

[source]
# you may need to adjust the command depending on your shell
command = "$SHELL -ic 'alias'"
output = "{split:=:0}"
