[metadata]
name = "dotfiles"
description = "A channel to select from your user's dotfiles"
requirements = ["fd", "bat"]

[source]
command = "fd -t f . $HOME/.config"

[preview]
command = "bat -n --color=always '{}'"

[keybindings]
enter = "actions:edit"
ctrl-l = "actions:edit"
ctrl-enter = "actions:edit"
ctrl-o = "actions:edit"
f12 = "actions:edit"

[actions.edit]
description = "Edit the selected dotfile"
command = "$EDITOR {} >/dev/tty"
mode = "execute"
