[metadata]
name = "files"
description = "A channel to select files and directories"
requirements = ["fd", "bat"]

[source]
command = [
  "fd -t f -H --exclude .git --exclude node_modules --exclude .venv --exclude .terraform",
]

[preview]
command = "bat -n --color=always '{}'"
env = { BAT_THEME = "ansi" }

[keybindings]
shortcut = "f1"
ctrl-l = "actions:edit"
ctrl-enter = "actions:edit"
ctrl-o = "actions:edit"

[actions.edit]
description = "Opens the selected entries with the default editor (falls back to vim)"
command = "$EDITOR {} >/dev/tty"
mode = "execute"
