[metadata]
name = "just-recipes"
description = "A channel to select recipes from Justfiles"
requirements = ["just"]

[source]
command = ["just --summary | tr '[:blank:]' '\n'"]

[preview]
command = "just -s {}"

[keybindings]
f5 = "actions:execute-recipe"

[actions.execute-recipe]
description = "Execute a justfile recipe"
command = "just {}"
mode = "execute"
