# Inserts a blank line between shell prompts
add_newline = false

[aws]
disabled = true

[gcloud]
disabled = true

[env_var.YAZI_LEVEL]
variable = "YAZI_LEVEL"
format = "[ğŸ¦†](yellow) "

[direnv]
disabled = false
format = '[$symbol$loaded]($style) '
detect_files = [".envrc", ".env"]
loaded_msg = "ğŸ‘"
unloaded_msg = "ğŸš«"

[git_metrics]
disabled = false

[cmd_duration]
disabled = false

[docker_context]
disabled = true

[kubernetes]
format = '[â›µ$context](green) '
disabled = true

[sudo]
style = 'bold yellow'
symbol = 'ğŸ§™'
disabled = false
